version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-integration-tests
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
      - MSSQL_PID=Developer
      - MSSQL_USER=bobs-service
      - MSSQL_PASSWORD=123456
    ports:
      - "1433:1433"
    volumes:
      - ./Scripts/SQLServer:/docker-entrypoint-initdb.d
    command: 
      - /bin/bash
      - -c 
      - |
        /opt/mssql/bin/sqlservr &
        sleep 30
        /opt/mssql-tools/bin/sqlcmd -U sa -P YourPassword123 -l 30 -e -i ./docker-entrypoint-initdb.d/create-database.sql
        /opt/mssql-tools/bin/sqlcmd -U sa -P YourPassword123 -l 30 -e -i ./docker-entrypoint-initdb.d/create-table.sql
        sleep infinity 
    networks:
      - test-network
    healthcheck:
      test: [ "CMD-SHELL", "sqlcmd -U sa -P YourPassword123 -d YourDatabase -Q \"SELECT 1\" || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  test-network:
    driver: bridge
